In [3]:
import pandas as pd
import nltk
from nltk.tokenize import wordpunct_tokenize
from nltk.corpus import stopwords
from unidecode import unidecode
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
dados = pd.read_csv("../WebScrapping/20260412_DadosDafiti.csv")

df = pd.DataFrame(dados)

df

,Marca,Cor,Vendedor,Produto,Tags,Preço Original,Preço Pix,Preço Parcelado,Quantidade de Parcelas
0,Jorge Bischoff,Marrom,Dafiti,Bota Feminina Jorge Bischoff Cano Alto Marrom,"Calçados,Calçados Femininos,Botas,Bota Montari...","R$ 1.199,00","R$ 589,99","R$ 627,65",10x
1,Arezzo,Preto,Dafiti,Bota Feminina Arezzo Cano Baixo Preta,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x
2,Arezzo,Marrom,Dafiti,Bota Feminina Arezzo Cano Baixo Marrom,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x
3,adidas Originals,Marrom,Dafiti,Tênis adidas Originals SL 72 OG Marrom,"Calçados,Calçados Femininos,Tênis,Tênis Casual","R$ 699,99","R$ 657,98","R$ 699,98",10x
4,adidas Originals,Preto,Dafiti,Tênis adidas Originals Superstar Slip On Preto,"Calçados,Calçados Femininos,Tênis,Slip On,Têni...","R$ 399,99","R$ 299,99","R$ 319,14",5x
...,...,...,...,...,...,...,...,...,...
1195,Usaflex,Preto,Dafiti,Sapatilha Feminina Usaflex Couro Preta,"Calçados,Calçados Femininos,Sapatilhas,Sapatil...","R$ 289,99","R$ 149,99","R$ 159,56",2x
1196,Vizzano,Marrom,Dafiti,Rasteira Vizzano Animal Print Marrom,"Calçados,Calçados Femininos,Rasteirinhas","R$ 119,90","R$ 59,99","R$ 63,82",1x
1197,Santa Lolla,Vermelho,Dafiti,Sapatilha Santa Lolla Aplicação Vermelha,"Calçados,Calçados Femininos,Sapatilhas,Sapatil...","R$ 269,90","R$ 169,99","R$ 180,84",3x
1198,VIA UNO,Preto,Dafiti,Mocassim Feminino Via Uno Detalhe Dourado Preto,"Calçados,Calçados Femininos,Mocassim","R$ 129,99","R$ 64,99","R$ 69,14",1x
1199,Santa Lolla,Marrom,Dafiti,Scarpin Feminino Santa Lolla Amarração Marrom,"Calçados,Calçados Femininos,Scarpin","R$ 249,90","R$ 169,99","R$ 180,84",3x

In [5]:

print(f"Antes: {len(df)} produtos")

df = df.drop_duplicates(subset="Produto").reset_index(drop=True)

print(f"Depois: {len(df)} produtos")

df.head()

Antes: 1200 produtos
Depois: 1101 produtos

,Marca,Cor,Vendedor,Produto,Tags,Preço Original,Preço Pix,Preço Parcelado,Quantidade de Parcelas
0,Jorge Bischoff,Marrom,Dafiti,Bota Feminina Jorge Bischoff Cano Alto Marrom,"Calçados,Calçados Femininos,Botas,Bota Montari...","R$ 1.199,00","R$ 589,99","R$ 627,65",10x
1,Arezzo,Preto,Dafiti,Bota Feminina Arezzo Cano Baixo Preta,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x
2,Arezzo,Marrom,Dafiti,Bota Feminina Arezzo Cano Baixo Marrom,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x
3,adidas Originals,Marrom,Dafiti,Tênis adidas Originals SL 72 OG Marrom,"Calçados,Calçados Femininos,Tênis,Tênis Casual","R$ 699,99","R$ 657,98","R$ 699,98",10x
4,adidas Originals,Preto,Dafiti,Tênis adidas Originals Superstar Slip On Preto,"Calçados,Calçados Femininos,Tênis,Slip On,Têni...","R$ 399,99","R$ 299,99","R$ 319,14",5x

In [6]:
def limpar_texto(texto):
    texto = texto.lower()
    texto = unidecode(texto)
    tokens = wordpunct_tokenize(texto)
    tokens = [token for token in tokens if token.isalnum()]
    return " ".join(tokens)


df["Produto_limpo"] = df["Produto"].apply(limpar_texto)

df[["Produto", "Produto_limpo"]].head()

,Produto,Produto_limpo
0,Bota Feminina Jorge Bischoff Cano Alto Marrom,bota feminina jorge bischoff cano alto marrom
1,Bota Feminina Arezzo Cano Baixo Preta,bota feminina arezzo cano baixo preta
2,Bota Feminina Arezzo Cano Baixo Marrom,bota feminina arezzo cano baixo marrom
3,Tênis adidas Originals SL 72 OG Marrom,tenis adidas originals sl 72 og marrom
4,Tênis adidas Originals Superstar Slip On Preto,tenis adidas originals superstar slip on preto

In [7]:
nltk.download("stopwords", quiet=True)

stopwords_pt = stopwords.words("portuguese")
stopwords_pt = [unidecode(palavra) for palavra in stopwords_pt]
stopwords_pt = set(stopwords_pt)


def remover_stopwords(texto):
    tokens = texto.split()
    tokens = [token for token in tokens if token not in stopwords_pt]
    return tokens


df["tokens_sem_stopwords"] = df["Produto_limpo"].apply(remover_stopwords)
df["Produto_sem_stopwords"] = df["tokens_sem_stopwords"].str.join(" ")

df[["Produto_limpo", "tokens_sem_stopwords", "Produto_sem_stopwords"]].head()

,Produto_limpo,tokens_sem_stopwords,Produto_sem_stopwords
0,bota feminina jorge bischoff cano alto marrom,"[bota, feminina, jorge, bischoff, cano, alto, ...",bota feminina jorge bischoff cano alto marrom
1,bota feminina arezzo cano baixo preta,"[bota, feminina, arezzo, cano, baixo, preta]",bota feminina arezzo cano baixo preta
2,bota feminina arezzo cano baixo marrom,"[bota, feminina, arezzo, cano, baixo, marrom]",bota feminina arezzo cano baixo marrom
3,tenis adidas originals sl 72 og marrom,"[tenis, adidas, originals, sl, 72, og, marrom]",tenis adidas originals sl 72 og marrom
4,tenis adidas originals superstar slip on preto,"[tenis, adidas, originals, superstar, slip, on...",tenis adidas originals superstar slip on preto

In [8]:
vectorizer = CountVectorizer()
matriz_bow = vectorizer.fit_transform(df["Produto_sem_stopwords"])

df_bow = pd.DataFrame(
    matriz_bow.toarray(),
    columns=vectorizer.get_feature_names_out()
)

df_bow.head()

,1080,11,1130,28,2k,3cm,480,530,6cm,72,...,vicenza,vinho,vintage,vizzano,warm,wh,white,wm,xl,ziper
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
colunas_com_numeros = [col for col in df_bow.columns if any(char.isdigit() for char in col)]

df_bow = df_bow.drop(columns=colunas_com_numeros)

print(f"{len(colunas_com_numeros)} colunas removidas")
df_bow.head()

12 colunas removidas

,aberta,ad,adidas,adistar,adorno,agulha,aju,ajuste,al,alca,...,vicenza,vinho,vintage,vizzano,warm,wh,white,wm,xl,ziper
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
metadados = df[["Marca", "Cor", "Vendedor", "Produto", "Tags", "Preço Original", "Preço Pix", "Preço Parcelado", "Quantidade de Parcelas"]].reset_index(drop=True)
bow_com_prefixo = df_bow.add_prefix("bow_").reset_index(drop=True)

df_final = pd.concat([metadados, bow_com_prefixo], axis=1)

df_final.head()

,Marca,Cor,Vendedor,Produto,Tags,Preço Original,Preço Pix,Preço Parcelado,Quantidade de Parcelas,bow_aberta,...,bow_vicenza,bow_vinho,bow_vintage,bow_vizzano,bow_warm,bow_wh,bow_white,bow_wm,bow_xl,bow_ziper
0,Jorge Bischoff,Marrom,Dafiti,Bota Feminina Jorge Bischoff Cano Alto Marrom,"Calçados,Calçados Femininos,Botas,Bota Montari...","R$ 1.199,00","R$ 589,99","R$ 627,65",10x,0,...,0,0,0,0,0,0,0,0,0,0
1,Arezzo,Preto,Dafiti,Bota Feminina Arezzo Cano Baixo Preta,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x,0,...,0,0,0,0,0,0,0,0,0,0
2,Arezzo,Marrom,Dafiti,Bota Feminina Arezzo Cano Baixo Marrom,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x,0,...,0,0,0,0,0,0,0,0,0,0
3,adidas Originals,Marrom,Dafiti,Tênis adidas Originals SL 72 OG Marrom,"Calçados,Calçados Femininos,Tênis,Tênis Casual","R$ 699,99","R$ 657,98","R$ 699,98",10x,0,...,0,0,0,0,0,0,0,0,0,0
4,adidas Originals,Preto,Dafiti,Tênis adidas Originals Superstar Slip On Preto,"Calçados,Calçados Femininos,Tênis,Slip On,Têni...","R$ 399,99","R$ 299,99","R$ 319,14",5x,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df_final.to_csv('20260421_DadosDafiti_NLP.csv', index=False)

In [12]:
colunas_bow = [coluna for coluna in df_final.columns if coluna.startswith("bow_")]

frequencia_palavras = df_final[colunas_bow].sum().sort_values(ascending=False)

print(f"Total de palavras diferentes: {len(frequencia_palavras)}")

frequencia_palavras.head(10)

Total de palavras diferentes: 456

bow_feminina    430
bow_feminino    278
bow_tenis       247
bow_sandalia    230
bow_salto       215
bow_marrom      162
bow_scarpin     151
bow_preta       149
bow_rasteira    145
bow_vizzano     143
dtype: int64

In [13]:
frequencia_palavras.tail(10)

bow_platino     1
bow_platinum    1
bow_pont        1
bow_flare       1
bow_ponteira    1
bow_laser       1
bow_faixa       1
bow_prateada    1
bow_bepece      1
bow_cut         1
dtype: int64

In [14]:
documentos_por_palavra = (df_final[colunas_bow] > 0).sum().sort_values(ascending=False)
documentos_por_palavra.index = documentos_por_palavra.index.str.replace("bow_", "", regex=False)

documentos_por_palavra.head(10)

feminina    430
feminino    278
tenis       247
sandalia    230
salto       215
marrom      162
scarpin     151
preta       149
rasteira    145
vizzano     143
dtype: int64

In [15]:
df_final["palavras_unicas"] = (df_final[colunas_bow] > 0).sum(axis=1)

df_final[["Produto", "palavras_unicas"]].sort_values("palavras_unicas", ascending=True).head(10)

                              Produto  palavras_unicas
25                Tênis Vizzano Preto                3
233   Sandália Vizzano Amarração Bege                4
180   Rasteira Usaflex Tratorada Bege                4
815  Tênis Vizzano Matelassê Caramelo                4
860         Tênis Asics Japan S Preto                4
102           Tênis Puma Palermo Rosa                4
303      Rasteira Anacapri Lisa Bordô                4
712         Tênis Asics JAPAN S Preto                4
99       Sandália Bebecê Bloco Branca                4
302   Alpargata Moleca Perfuros Preta                4

# TF-IDF

In [16]:
matriz_bow_df = df_final[colunas_bow].copy()
matriz_bow_df.columns = matriz_bow_df.columns.str.replace("bow_", "", regex=False)

matriz_bow_df.head()

,aberta,ad,adidas,adistar,adorno,agulha,aju,ajuste,al,alca,...,vicenza,vinho,vintage,vizzano,warm,wh,white,wm,xl,ziper
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
total_palavras_por_produto = matriz_bow_df.sum(axis=1)

matriz_tf = matriz_bow_df.div(total_palavras_por_produto, axis=0)

matriz_tf.head()

,aberta,ad,adidas,adistar,adorno,agulha,aju,ajuste,al,alca,...,vicenza,vinho,vintage,vizzano,warm,wh,white,wm,xl,ziper
0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.166667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
produto = 0

print(df_final.loc[produto, "Produto"])

matriz_tf.loc[produto].sort_values(ascending=False).head(10)

Bota Feminina Jorge Bischoff Cano Alto Marrom

marrom       0.142857
bota         0.142857
bischoff     0.142857
jorge        0.142857
feminina     0.142857
cano         0.142857
alto         0.142857
peludo       0.000000
perfume      0.000000
perfurado    0.000000
Name: 0, dtype: float64

In [20]:
import numpy as np

N = len(matriz_bow_df)
documentos_por_termo = (matriz_bow_df > 0).sum(axis=0)

idf = np.log(N / documentos_por_termo)

df_idf = pd.DataFrame({
    "documentos_com_o_termo": documentos_por_termo,
    "idf": idf
}).sort_values("idf", ascending=False)

df_idf.head(10)

          documentos_com_o_termo       idf
farm                           1  7.003974
clog                           1  7.003974
delicado                       1  7.003974
design                         1  7.003974
rubi                           1  7.003974
lover                          1  7.003974
detalh                         1  7.003974
texturi                        1  7.003974
spezial                        1  7.003974
doura                          1  7.003974

In [21]:
matriz_tfidf = matriz_tf.mul(idf, axis=1)

matriz_tfidf.head()

,aberta,ad,adidas,adistar,adorno,agulha,aju,ajuste,al,alca,...,vicenza,vinho,vintage,vizzano,warm,wh,white,wm,xl,ziper
0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.668040,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.572606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
produto = 10

print(df_final.loc[produto, "Produto"])

matriz_tfidf.loc[produto].sort_values(ascending=False).head(10)

Sandália Melissa Free Print Platform Ad Caramelo

platform    1.000568
ad          0.901547
free        0.901547
print       0.770648
melissa     0.558990
caramelo    0.413300
sandalia    0.223699
oliva       0.000000
peludo      0.000000
off         0.000000
Name: 10, dtype: float64

In [24]:
tfidf_com_prefixo = matriz_tfidf.add_prefix("tfidf_").reset_index(drop=True)

df_final_tfidf = pd.concat([metadados, tfidf_com_prefixo], axis=1)

df_final_tfidf.head()

,Marca,Cor,Vendedor,Produto,Tags,Preço Original,Preço Pix,Preço Parcelado,Quantidade de Parcelas,tfidf_aberta,...,tfidf_vicenza,tfidf_vinho,tfidf_vintage,tfidf_vizzano,tfidf_warm,tfidf_wh,tfidf_white,tfidf_wm,tfidf_xl,tfidf_ziper
0,Jorge Bischoff,Marrom,Dafiti,Bota Feminina Jorge Bischoff Cano Alto Marrom,"Calçados,Calçados Femininos,Botas,Bota Montari...","R$ 1.199,00","R$ 589,99","R$ 627,65",10x,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Arezzo,Preto,Dafiti,Bota Feminina Arezzo Cano Baixo Preta,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Arezzo,Marrom,Dafiti,Bota Feminina Arezzo Cano Baixo Marrom,"Calçados,Calçados Femininos,Botas,Bota Cano Curto","R$ 599,90","R$ 563,90","R$ 599,89",10x,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,adidas Originals,Marrom,Dafiti,Tênis adidas Originals SL 72 OG Marrom,"Calçados,Calçados Femininos,Tênis,Tênis Casual","R$ 699,99","R$ 657,98","R$ 699,98",10x,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,adidas Originals,Preto,Dafiti,Tênis adidas Originals Superstar Slip On Preto,"Calçados,Calçados Femininos,Tênis,Slip On,Têni...","R$ 399,99","R$ 299,99","R$ 319,14",5x,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer_tfidf = TfidfVectorizer()
matriz_tfidf_sklearn = vectorizer_tfidf.fit_transform(df["Produto_sem_stopwords"])

df_tfidf_sklearn = pd.DataFrame(
    matriz_tfidf_sklearn.toarray(),
    columns=vectorizer_tfidf.get_feature_names_out()
)

df_tfidf_sklearn.head()

,1080,11,1130,28,2k,3cm,480,530,6cm,72,...,vicenza,vinho,vintage,vizzano,warm,wh,white,wm,xl,ziper
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.488595,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
from pathlib import Path

pasta_dados = Path("../dados")
pasta_dados.mkdir(exist_ok=True)

# Dados completos: metadados + texto original + texto limpo + texto sem stopwords
df_completo = df[['Marca', 'Cor', 'Vendedor', 'Produto', 'Tags', 'Preço Original',
       'Preço Pix', 'Preço Parcelado', 'Quantidade de Parcelas', "Produto", "Produto_limpo", "Produto_sem_stopwords"]]
df_completo.to_csv(pasta_dados / "produtos.csv", index=False)

# Bag of Words (metadados + colunas bow_)
df_final.to_csv(pasta_dados / "bow.csv", index=False)

# TF-IDF (metadados + colunas tfidf_)
df_final_tfidf.to_csv(pasta_dados / "tfidf.csv", index=False)

print(f"produtos completas: {pasta_dados / 'produtos.csv'} (shape={df_completo.shape})")
print(f"Bag of Words:       {pasta_dados / 'bow.csv'}      (shape={df_final.shape})")
print(f"TF-IDF:             {pasta_dados / 'tfidf.csv'}    (shape={df_final_tfidf.shape})")

produtos completas: ../dados/produtos.csv (shape=(1101, 12))
Bag of Words:       ../dados/bow.csv      (shape=(1101, 466))
TF-IDF:             ../dados/tfidf.csv    (shape=(1101, 465))

Index(['Marca', 'Cor', 'Vendedor', 'Produto', 'Tags', 'Preço Original',
       'Preço Pix', 'Preço Parcelado', 'Quantidade de Parcelas',
       'Produto_limpo', 'tokens_sem_stopwords', 'Produto_sem_stopwords'],
      dtype='object')